#!/usr/bin/env python3
"""
Build src/games/WordleWords.h, the word data of the built-in Wordle game.

Two lists come out of it:

- every word the game accepts as a guess: all five-letter a-z headwords of a
  StarDict English dictionary plus the five-letter word forms of its .syn file;
- the words the game picks as answers: the candidates of
  scripts/wordle/answer_candidates.txt that are headwords with a substantial
  entry, without plain plurals and -ed forms.

Guesses are stored two bytes a word: the words are sorted, grouped by their
first two letters (kBucketStart) and each keeps only its last three letters as
a base-26 number (kTail). Answers are indices into that list.

Usage:
    python scripts/build_wordle_words.py --dict <folder with the .idx and .syn>
"""

import argparse
import re
import struct
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CANDIDATES = REPO / "scripts" / "wordle" / "answer_candidates.txt"
OUTPUT = REPO / "src" / "games" / "WordleWords.h"

FIVE = re.compile(rb"^[a-z]{5}$")
FOUR = re.compile(rb"^[a-z]{4}$")
THREE = re.compile(rb"^[a-z]{3}$")
# A shorter entry than this is usually a rare word, a variant spelling or a bare word form.
MIN_ANSWER_ENTRY_BYTES = 200
# Kept out of the answers only; they stay valid guesses.
NOT_AN_ANSWER = {"bitch", "bosom", "booby", "busty", "horny", "pansy", "pussy", "semen", "slave", "sissy", "urine", "whore"}


def stardict_index(path: Path, tail_bytes: int):
    data = path.read_bytes()
    position = 0
    while position < len(data):
        end = data.index(b"\0", position)
        yield data[position:end], data[end + 1 : end + 1 + tail_bytes]
        position = end + 1 + tail_bytes


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dict", required=True, type=Path, help="folder holding one StarDict .idx and .syn")
    args = parser.parse_args()

    idx_path = next(args.dict.glob("*.idx"))
    syn_path = next(args.dict.glob("*.syn"))

    entry_bytes = {}
    short_headwords = set()
    for word, tail in stardict_index(idx_path, 8):
        if FIVE.match(word):
            size = struct.unpack(">II", tail)[1]
            entry_bytes[word.decode()] = max(size, entry_bytes.get(word.decode(), 0))
        elif FOUR.match(word) or THREE.match(word):
            short_headwords.add(word.decode())
    forms = {word.decode() for word, _ in stardict_index(syn_path, 4) if FIVE.match(word)}

    guesses = sorted(set(entry_bytes) | forms)
    assert len(guesses) < 65536, "answer indices are 16 bit"
    index_of = {word: i for i, word in enumerate(guesses)}

    def is_plain_inflection(word: str) -> bool:
        if word.endswith("s") and not word.endswith("ss") and word[:-1] in short_headwords:
            return True
        return word.endswith("ed") and (word[:-1] in short_headwords or word[:-2] in short_headwords)

    candidates = [line.strip().lower() for line in CANDIDATES.read_text(encoding="utf-8").splitlines()]
    answers = sorted(
        word
        for word in candidates
        if word
        and not word.startswith("#")
        and entry_bytes.get(word, 0) >= MIN_ANSWER_ENTRY_BYTES
        and word not in NOT_AN_ANSWER
        and not is_plain_inflection(word)
    )

    bucket_start = [0] * 677
    for word in guesses:
        bucket = (ord(word[0]) - 97) * 26 + (ord(word[1]) - 97)
        bucket_start[bucket + 1] += 1
    for bucket in range(676):
        bucket_start[bucket + 1] += bucket_start[bucket]
    tails = [((ord(w[2]) - 97) * 26 + (ord(w[3]) - 97)) * 26 + (ord(w[4]) - 97) for w in guesses]

    def rows(values, per_row=16):
        lines = []
        for start in range(0, len(values), per_row):
            lines.append("    " + ", ".join(str(v) for v in values[start : start + per_row]) + ",")
        return "\n".join(lines)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        f"""#pragma once

#include <cstdint>

// Generated by scripts/build_wordle_words.py. Do not edit.
// {len(guesses)} accepted guesses, {len(answers)} answers.
//
// Guesses are sorted and grouped by their first two letters: kBucketStart[b] is
// the index of the first word whose first two letters are bucket b
// (letter0 * 26 + letter1). kTail holds the last three letters of each word as
// a base-26 number. kAnswers indexes kTail.

namespace wordle_words {{

constexpr uint16_t kWordCount = {len(guesses)};
constexpr uint16_t kAnswerCount = {len(answers)};

static const uint16_t kBucketStart[677] = {{
{rows(bucket_start)}
}};

static const uint16_t kTail[kWordCount] = {{
{rows(tails)}
}};

static const uint16_t kAnswers[kAnswerCount] = {{
{rows([index_of[word] for word in answers])}
}};

}}  // namespace wordle_words
""",
        encoding="utf-8",
        newline="\n",
    )
    print(f"{OUTPUT.relative_to(REPO)}: {len(guesses)} guesses, {len(answers)} answers")
    print("sample answers:", " ".join(answers[:: max(1, len(answers) // 40)]))


if __name__ == "__main__":
    main()
