#!/usr/bin/env python3
"""
Draw the Home menu icon for Apps (four rounded squares) and write it as
src/components/icons/appsIcon.h in the freeink::Icon format used by the other
menu icons: one bit per pixel, most significant bit first, 0 = ink.

Usage:
    python scripts/generate_apps_icon.py
"""

from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "components" / "icons" / "appsIcon.h"
SUPERSAMPLE = 4


def draw(size):
    """Returns rows of booleans (True = ink) for a size x size icon."""
    margin = size * 0.14
    gap = size * 0.1
    side = (size - 2 * margin - gap) / 2
    stroke = size / 12.0
    radius = size * 0.09
    # The four squares; the bottom right one is solid, like an app being open.
    squares = [(margin, margin, False), (margin + side + gap, margin, False), (margin, margin + side + gap, False),
               (margin + side + gap, margin + side + gap, True)]

    def inside_square(x, y, left, top, inset):
        lo_x, lo_y = left + inset, top + inset
        hi_x, hi_y = left + side - inset, top + side - inset
        r = max(0.0, radius - inset)
        if not (lo_x <= x <= hi_x and lo_y <= y <= hi_y):
            return False
        cx = min(max(x, lo_x + r), hi_x - r)
        cy = min(max(y, lo_y + r), hi_y - r)
        return (x - cx) ** 2 + (y - cy) ** 2 <= r**2 + 1e-9

    rows = []
    for py in range(size):
        row = []
        for px in range(size):
            covered = 0
            for sy in range(SUPERSAMPLE):
                for sx in range(SUPERSAMPLE):
                    x = px + (sx + 0.5) / SUPERSAMPLE
                    y = py + (sy + 0.5) / SUPERSAMPLE
                    ink = False
                    for left, top, solid in squares:
                        if inside_square(x, y, left, top, 0.0) and (solid or not inside_square(x, y, left, top, stroke)):
                            ink = True
                    covered += 1 if ink else 0
            row.append(covered * 2 >= SUPERSAMPLE * SUPERSAMPLE)
        rows.append(row)
    return rows


def to_bytes(rows):
    data = []
    for row in rows:
        for start in range(0, len(row), 8):
            byte = 0
            for bit in range(8):
                ink = start + bit < len(row) and row[start + bit]
                byte = (byte << 1) | (0 if ink else 1)
            data.append(byte)
    return data


def main() -> None:
    parts = [
        "#pragma once\n",
        '#include "Icon.h"\n',
        "// Generated by scripts/generate_apps_icon.py. Do not edit.\n// apps: four rounded squares.",
    ]
    for size in (24, 32):
        data = to_bytes(draw(size))
        lines = []
        for start in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[start : start + 16]) + ",")
        parts.append(
            f"static const uint8_t icon_apps_{size}_bits[] = {{\n" + "\n".join(lines) + "\n};\n"
            f"static const freeink::Icon icon_apps_{size} = {{{size}, {size}, {size // 2}, icon_apps_{size}_bits}};"
        )
    OUTPUT.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    for row in draw(32):
        print("".join("#" if ink else "." for ink in row))


if __name__ == "__main__":
    main()
