#!/usr/bin/env python3
"""
Render the large letters and digits of the built-in games and write them as
src/activities/apps/GameGlyphs.h.

The UI fonts stop at 12 pt, which leaves a Wordle tile or a Sudoku cell mostly
empty. These glyphs are drawn once here from Lexend Deca (already in the
repository, SIL Open Font License) at the size the game screens want:

- capital letters A-Z, bold, for the Wordle tiles;
- digits 1-9, bold (printed clues) and regular (your own digits), for Sudoku.

Each glyph is a one-bit bitmap, rows padded to whole bytes, most significant
bit first, 1 = ink. All glyphs of a set share one height, so the caller only
has to centre a box.

Usage:
    python scripts/generate_game_glyphs.py        (needs Pillow)
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
FONTS = REPO / "lib" / "EpdFont" / "builtinFonts" / "source" / "LexendDeca"
OUTPUT = REPO / "src" / "activities" / "apps" / "GameGlyphs.h"

SETS = [
    # name, characters, font file, height of a capital letter or digit in pixels
    ("Letter", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "LexendDeca-Bold.ttf", 34),
    ("DigitBold", "123456789", "LexendDeca-Bold.ttf", 28),
    ("DigitRegular", "123456789", "LexendDeca-Regular.ttf", 28),
]


def font_for_height(path: Path, reference: str, height: int) -> ImageFont.FreeTypeFont:
    """The largest font size whose reference glyph is no taller than height."""
    size = height
    best = ImageFont.truetype(str(path), size)
    while True:
        font = ImageFont.truetype(str(path), size)
        top, bottom = font.getbbox(reference)[1], font.getbbox(reference)[3]
        if bottom - top > height:
            return best
        best = font
        size += 1


def render_set(characters: str, font: ImageFont.FreeTypeFont, reference: str):
    """Returns (rows per glyph, list of (width, bitmap rows))."""
    ref_top = font.getbbox(reference)[1]
    ref_bottom = font.getbbox(reference)[3]
    # Room below the baseline for the tail of Q.
    lowest = max(font.getbbox(c)[3] for c in characters)
    rows = max(ref_bottom, lowest) - ref_top
    glyphs = []
    for character in characters:
        left, _, right, _ = font.getbbox(character)
        width = right - left
        image = Image.new("L", (width, rows), 0)
        ImageDraw.Draw(image).text((-left, -ref_top), character, font=font, fill=255)
        pixels = image.load()
        glyphs.append((width, [[pixels[x, y] >= 128 for x in range(width)] for y in range(rows)]))
    return rows, ref_bottom - ref_top, glyphs


def pack(rows):
    data = []
    for row in rows:
        for start in range(0, len(row), 8):
            byte = 0
            for bit in range(8):
                byte = (byte << 1) | (1 if start + bit < len(row) and row[start + bit] else 0)
            data.append(byte)
    return data


def main() -> None:
    parts = [
        "#pragma once\n",
        "#include <cstdint>\n",
        "// Generated by scripts/generate_game_glyphs.py from Lexend Deca (SIL Open Font License). Do not edit.",
        "//",
        "// One-bit glyphs: rows padded to whole bytes, most significant bit first, 1 = ink.",
        "// Every glyph of a set is k<Set>Rows high; the first k<Set>Cap rows hold a capital",
        "// letter or digit, the rest is room below the baseline.\n",
        "namespace gameglyphs {\n",
        "struct Glyph {\n  uint16_t offset;  // into the set's bitmap bytes\n  uint8_t width;\n};\n",
    ]
    for name, characters, font_file, height in SETS:
        reference = "H" if characters[0].isalpha() else "8"
        font = font_for_height(FONTS / font_file, reference, height)
        rows, cap, glyphs = render_set(characters, font, reference)
        data = []
        table = []
        for width, bitmap in glyphs:
            table.append((len(data), width))
            data.extend(pack(bitmap))
        lines = []
        for start in range(0, len(data), 20):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[start : start + 20]) + ",")
        parts.append(f"// {characters}  ({font_file})")
        parts.append(f"constexpr int k{name}Rows = {rows};")
        parts.append(f"constexpr int k{name}Cap = {cap};")
        parts.append(f"static const uint8_t k{name}Bits[] = {{\n" + "\n".join(lines) + "\n};")
        parts.append(
            f"static const Glyph k{name}Glyphs[{len(table)}] = {{\n    "
            + ", ".join(f"{{{offset}, {width}}}" for offset, width in table)
            + ",\n};\n"
        )
        print(f"{name}: {len(table)} glyphs, {rows} rows (cap {cap}), {len(data)} bytes")
    parts.append("}  // namespace gameglyphs")
    OUTPUT.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print("wrote", OUTPUT.relative_to(REPO))


if __name__ == "__main__":
    main()
